# Generated by Django 5.0.2 on 2024-02-14 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricresistancetest',
            name='induction_motor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electric_resistance_test', to='motor_testing.inductionmotor'),
        ),
        migrations.AlterField(
            model_name='insulationresistancetest',
            name='induction_motor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insulation_resistance_test', to='motor_testing.inductionmotor'),
        ),
        migrations.AlterField(
            model_name='noloadtest',
            name='induction_motor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_load_test', to='motor_testing.inductionmotor'),
        ),
        migrations.AlterField(
            model_name='performancedeterminationtest',
            name='induction_motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_determination_test', to='motor_testing.inductionmotor'),
        ),
        migrations.AlterField(
            model_name='temperaturerisetest',
            name='induction_motor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_rise_test', to='motor_testing.inductionmotor'),
        ),
        migrations.AlterField(
            model_name='withstandvoltageactest',
            name='induction_motor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withstand_voltage_ac_test', to='motor_testing.inductionmotor'),
        ),
    ]
