# Generated by Django 5.0.2 on 2024-02-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_testing', '0002_alter_electricresistancetest_induction_motor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inductionmotor',
            name='Withstand_voltage',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='Withstand_voltage_test_status',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='electric_resistance',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='electric_resistance_test_status',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='insulation_resistance',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='insulation_resistance_test_status',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='no_load',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='no_load_test_status',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='performance_determination',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='performance_determination_test_status',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='temperature_rise_nominal_condition',
        ),
        migrations.RemoveField(
            model_name='inductionmotor',
            name='temperature_rise_nominal_condition_test_status',
        ),
        migrations.CreateModel(
            name='PerformanceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('electric_resistance_test', 'Electric Resistance Test'), ('temperature_rise_test', 'Temperature Rise Test'), ('performance_determination_test', 'Performance Determination Test'), ('no_load_test', 'No Load Test'), ('withstand_voltage_ac_test', 'Withstand Voltage AC Test'), ('insulation_resistance_test', 'Insulation Resistance Test')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('NOT_FOUND', 'Not Found')], max_length=10)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_tests', to='motor_testing.inductionmotor')),
            ],
        ),
    ]
