# Generated by Django 5.0.2 on 2024-02-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_testing', '0003_remove_inductionmotor_withstand_voltage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancetest',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='performancetest',
            name='routine',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='performancetest',
            name='special',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='performancetest',
            name='type',
            field=models.BooleanField(null=True),
        ),
    ]
