# Generated by Django 5.0.2 on 2024-02-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_testing', '0004_performancetest_page_number_performancetest_routine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionmotor',
            name='report_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inductionmotor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETE', 'DELETED')], default='ACTIVE', max_length=7),
        ),
    ]
