# Generated by Django 5.0.2 on 2024-02-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_testing', '0005_inductionmotor_report_link_inductionmotor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductionmotor',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('DELETE', 'DELETED')], default='ACTIVE', max_length=7),
        ),
    ]
