# Generated by Django 5.0.2 on 2024-02-22 12:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_testing', '0006_alter_inductionmotor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancedeterminationtest',
            name='cos',
        ),
        migrations.RemoveField(
            model_name='performancedeterminationtest',
            name='current',
        ),
        migrations.RemoveField(
            model_name='performancedeterminationtest',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='performancedeterminationtest',
            name='load',
        ),
        migrations.RemoveField(
            model_name='performancedeterminationtest',
            name='slip',
        ),
        migrations.RemoveField(
            model_name='performancedeterminationtest',
            name='speed',
        ),
        migrations.AlterField(
            model_name='performancedeterminationtest',
            name='induction_motor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_determination_test', to='motor_testing.inductionmotor'),
        ),
        migrations.CreateModel(
            name='PerformanceTestParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('slip', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cos', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('performance_determination_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='motor_testing.performancedeterminationtest')),
            ],
        ),
    ]
