# Generated by Django 5.0.2 on 2024-02-28 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_testing', '0008_performancedeterminationtest_performance_25_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancedeterminationtest',
            name='performance_100',
            field=models.FileField(blank=True, null=True, upload_to='uploads/100/'),
        ),
        migrations.AddField(
            model_name='performancedeterminationtest',
            name='performance_50',
            field=models.FileField(blank=True, null=True, upload_to='uploads/50/'),
        ),
        migrations.AddField(
            model_name='performancedeterminationtest',
            name='performance_75',
            field=models.FileField(blank=True, null=True, upload_to='uploads/75/'),
        ),
        migrations.AlterField(
            model_name='performancedeterminationtest',
            name='performance_25',
            field=models.FileField(blank=True, null=True, upload_to='uploads/25/'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('induction_motor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='motor_testing.inductionmotor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
