# Generated by Django 5.0.2 on 2024-03-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0011_alter_performancetest_test_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancetest",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("electric_resistance_test", "Electric Resistance Test"),
                    ("temperature_rise_test", "Temperature Rise Test"),
                    (
                        "performance_determination_test",
                        "Performance Determination Test",
                    ),
                    ("no_load_test", "No Load Test"),
                    ("withstand_voltage_ac_test", "Withstand Voltage AC Test"),
                    ("insulation_resistance_test", "Insulation Resistance Test"),
                    ("lock_rotor_test", "Lock Rotor Test"),
                ],
                max_length=50,
            ),
        ),
    ]
