# Generated by Django 5.0.2 on 2024-03-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0012_alter_performancetest_test_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_load_test", models.FileField(upload_to="uploads/")),
                ("performance_determination", models.FileField(upload_to="uploads/")),
                ("lock_rotor_test", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
