# Generated by Django 5.0.2 on 2024-03-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0014_uploadedfile_delete_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
