# Generated by Django 5.0.2 on 2024-03-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0015_yourmodel_delete_uploadedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_field", models.FileField(upload_to="uploads/")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="YourModel",
        ),
    ]
