# Generated by Django 5.0.2 on 2024-03-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0016_mymodel_delete_yourmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
