# Generated by Django 5.0.2 on 2024-03-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0017_config_delete_mymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_load_test", models.CharField(max_length=100)),
                ("performance_determination", models.CharField(max_length=100)),
                ("lock_rotor_test", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Config",
        ),
    ]
