# Generated by Django 5.0.2 on 2024-03-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motor_testing", "0018_configuration_delete_config")]

    operations = [
        migrations.AddField(
            model_name="inductionmotor",
            name="director_cerad",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="inductionmotor",
            name="lab_instructor",
            field=models.CharField(default="", max_length=50),
        ),
    ]
