# Generated by Django 5.0.2 on 2024-03-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0021_noloadtest_report_date_delete_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="noloadtest",
            name="mdb_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="noloadtest",
            name="report_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
