# Generated by Django 5.0.2 on 2024-03-08 10:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0022_noloadtest_mdb_data_alter_noloadtest_report_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockrotortest",
            name="current",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="lockrotortest",
            name="mdb_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lockrotortest",
            name="report_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="lockrotortest",
            name="speed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="lockrotortest",
            name="voltage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
