# Generated by Django 5.0.2 on 2024-03-08 10:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0023_lockrotortest_current_lockrotortest_mdb_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockrotortest",
            name="power",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
