# Generated by Django 5.0.2 on 2024-03-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motor_testing", "0024_lockrotortest_power")]

    operations = [
        migrations.AddField(
            model_name="noloadtest",
            name="_report_date",
            field=models.DateField(blank=True, null=True),
        )
    ]
