# Generated by Django 5.0.2 on 2024-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "motor_testing",
            "0028_alter_electricresistancetest_resistance_ohm_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="performancedeterminationtest",
            name="mdb_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
