# Generated by Django 5.0.2 on 2024-03-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_testing', '0028_alter_electricresistancetest_resistance_ohm_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancetestparameters',
            name='slip',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
