# Generated by Django 5.0.2 on 2024-03-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("motor_testing", "0029_performancedeterminationtest_mdb_data")]

    operations = [
        migrations.RenameField(
            model_name="noloadtest", old_name="_report_date", new_name="reported_date"
        )
    ]
