# Generated by Django 5.0.2 on 2024-03-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0030_rename__report_date_noloadtest_reported_date"),
        ("motor_testing", "0031_alter_performancetestparameters_cos_and_more"),
    ]

    operations = []
