# Generated by Django 5.0.2 on 2024-03-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("motor_testing", "0032_merge_20240314_0452")]

    operations = [
        migrations.RenameField(
            model_name="lockrotortest",
            old_name="_report_date",
            new_name="reported_date",
        )
    ]
