# Generated by Django 5.0.2 on 2024-03-15 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0033_rename__report_date_lockrotortest_reported_date")
    ]

    operations = [
        migrations.AlterField(
            model_name="lockrotortest",
            name="reported_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="noloadtest",
            name="reported_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="performancedeterminationtest",
            name="report_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
