# Generated by Django 5.0.2 on 2024-05-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "motor_testing",
            "0036_alter_electricresistancetest_ambient_temperature_c_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="electricresistancetest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="insulationresistancetest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="lockrotortest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="noloadtest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="performancedeterminationtest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="temperaturerisetest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="withstandvoltageactest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
