# Generated by Django 5.0.2 on 2024-05-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motor_testing", "0037_electricresistancetest_remarks_and_more")]

    operations = [
        migrations.AlterField(
            model_name="performancedeterminationtest",
            name="remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        )
    ]
