# Generated by Django 5.0.2 on 2024-05-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0038_alter_performancedeterminationtest_remarks")
    ]

    operations = [
        migrations.AlterField(
            model_name="electricresistancetest",
            name="remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="insulationresistancetest",
            name="remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="lockrotortest",
            name="remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="noloadtest",
            name="remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="temperaturerisetest",
            name="remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="withstandvoltageactest",
            name="remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
