# Generated by Django 5.0.2 on 2024-05-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0039_alter_electricresistancetest_remarks_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="noloadtest",
            name="direction_of_rotation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CLOCKWISE", "Clockwise"),
                    ("ANTI_CLOCKWISE", "Anti Clockwise"),
                ],
                default=("CLOCKWISE", "Clockwise"),
                max_length=20,
                null=True,
            ),
        )
    ]
