# Generated by Django 5.0.2 on 2024-05-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motor_testing", "0041_alter_electricresistancetest_remarks")]

    operations = [
        migrations.AlterField(
            model_name="insulationresistancetest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="lockrotortest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="noloadtest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="performancedeterminationtest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="temperaturerisetest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="withstandvoltageactest",
            name="remarks",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
