# Generated by Django 5.0.2 on 2024-05-14 11:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0045_alter_inductionmotor_ambient_temperature_c_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="electricresistancetest",
            name="ambient_temperature_C",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="inductionmotor",
            name="service_factor",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
