# Generated by Django 5.0.2 on 2024-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "motor_testing",
            "0046_alter_electricresistancetest_ambient_temperature_c_and_more",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="performancedeterminationtest",
            name="frequency",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="performancedeterminationtest",
            name="nominal_t",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="performancedeterminationtest",
            name="voltage",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
    ]
