# Generated by Django 5.0.2 on 2024-05-14 11:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0047_alter_performancedeterminationtest_frequency_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="electricresistancetest",
            name="resistance_ohm_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        )
    ]
