# Generated by Django 5.0.2 on 2024-05-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_testing", "0048_alter_electricresistancetest_resistance_ohm_1")
    ]

    operations = [
        migrations.AlterField(
            model_name="inductionmotor",
            name="power",
            field=models.PositiveIntegerField(blank=True, default=2),
            preserve_default=False,
        )
    ]
