# Generated by Django 5.0.2 on 2024-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motor_testing", "0049_alter_inductionmotor_power")]

    operations = [
        migrations.AlterField(
            model_name="inductionmotor",
            name="power",
            field=models.PositiveIntegerField(),
        )
    ]
