# Generated by Django 5.0.2 on 2024-05-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motor_testing", "0050_alter_inductionmotor_power")]

    operations = [
        migrations.AddField(
            model_name="inductionmotor",
            name="test_type",
            field=models.CharField(
                choices=[("45kw", "up to 45KW"), ("5kw", "5KW")],
                default=("45kw", "up to 45KW"),
                max_length=6,
            ),
        )
    ]
