# Generated by Django 5.0.2 on 2024-05-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_testing', '0051_inductionmotor_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductionmotor',
            name='test_type',
            field=models.CharField(choices=[('45kw', '45KW'), ('5kw', 'Up to 5KW')], default=('45kw', '45KW'), max_length=6),
        ),
    ]
