# Generated by Django 5.0.2 on 2024-05-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("motor_testing", "0055_remove_inductionmotor_motor_test_type")]

    operations = [
        migrations.AddField(
            model_name="inductionmotor",
            name="test_type",
            field=models.CharField(
                choices=[("45kw", "upto 45KV"), ("5kw", "5KV")],
                default=("45kw", "upto 45KV"),
                max_length=6,
            ),
        )
    ]
